name: Create Repo
on:
  workflow_dispatch:
    inputs:
      project-name:
        description: 'Name of the project'
        required: true
        default: ''
      project-slug:
        description: 'Slug of the project'
        required: true
        default: ''
      theme-name:
        description: 'Parent theme name'
        required: true
        default: ''
      child-name:
        description: 'Child theme name'
        required: true
        default: ''

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:       
      - name: Replace Variables
        uses: falnyr/replace-env-vars-action@master
        env:
          PROJECT_NAME: "${{ github.event.inputs.project-name }}"
          PROJECT_SLUG: "${{ github.event.inputs.project-slug }}"
          THEME_NAME: "${{ github.event.inputs.theme-name }}"
          CHILD_THEME_NAME: "${{ github.event.inputs.child-name }}"
        with:
          filename: index.html
          
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v1


